"""Versioned M5b corpus: local reviewed M3 photos + original CC0 synthetic probes. No downloads."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import json,hashlib,sys,io
root=Path(__file__).resolve().parents[2];src=root/'tests/fixtures/subject-corpus/v1';out=root/'tests/fixtures/upscale-corpus/v1';out.mkdir(parents=True,exist_ok=True)
raw=Path(sys.argv[1]);raw.mkdir(parents=True,exist_ok=True)
parents={x['id']:x for x in json.loads((src/'manifest.json').read_text())['cases']};cases=[]
def add(name,category,im,parent=None,derived=None):
 im=im.convert('RGBA');path=out/(name+'.png');im.save(path);(raw/(name+'.bin')).write_bytes(im.tobytes())
 cases.append(dict(id=name,category=category,width=im.width,height=im.height,file=path.name,sha256=hashlib.sha256(path.read_bytes()).hexdigest(),source=parents[parent]['source'] if parent else 'Original synthetic fixture generated by scripts/m5b/create-corpus.py',license=parents[parent]['license'] if parent else 'CC0-1.0',derived=derived))
add('photo','natural photograph',Image.open(src/'object.png').resize((301,201),Image.Resampling.LANCZOS),'object','coffee scene reduced to odd dimensions')
add('portrait','portrait',Image.open(src/'person.png').resize((256,256),Image.Resampling.LANCZOS),'person','NASA portrait reduced')
add('fur','animal/fur',Image.open(src/'fur.png').resize((225,150),Image.Resampling.LANCZOS),'fur','cat reduced')
add('architecture','architecture',Image.open(src/'people.png').resize((384,256),Image.Resampling.LANCZOS),'people','colonnade scene; also contains people')
im=Image.new('RGB',(321,181),'#ddddcc');d=ImageDraw.Draw(im);d.rectangle((20,20,300,140),fill='#175980');d.text((30,40),'PHOTO SUITE 0123456789',fill='white');d.text((30,65),'KEEP LEFT / EXIT 42',fill='#ffff22');add('text','text/signage',im)
im=Image.new('RGB',(321,201),'#25292d');d=ImageDraw.Draw(im);d.rectangle((0,0,320,24),fill='#444b52');d.text((8,8),'File  Edit  Image  View',fill='white');d.rectangle((8,36,100,188),fill='#555555');d.text((15,48),'Layers\nOpacity 100%\nNormal\nBackground',fill='white');d.rectangle((110,36,305,188),fill='#b2cbd4');add('ui','UI/screenshot',im)
im=Image.new('RGB',(257,193),'white');d=ImageDraw.Draw(im)
for y in range(12,185,12):d.line((10,y,247,190-y),fill='black',width=1)
d.ellipse((50,20,210,180),outline='black',width=2);add('line-art','line art',im)
im=Image.new('RGB',(257,193),'#f2d3ad');d=ImageDraw.Draw(im);d.polygon([(0,190),(80,22),(160,190)],fill='#397c83');d.ellipse((143,22,230,109),fill='#e79132');d.rectangle((132,125,225,170),fill='#ba5377');add('illustration','illustration',im)
photo=Image.open(src/'object.png').convert('RGB').resize((151,101));b=io.BytesIO();photo.save(b,format='JPEG',quality=18);add('jpeg','low-resolution JPEG',Image.open(io.BytesIO(b.getvalue())),'object','151x101 JPEG quality18 then decoded')
im=Image.new('RGB',(257,193),'#808080');d=ImageDraw.Draw(im)
for x in range(0,257,4):d.line((x,0,x,192),fill='white' if x%8 else 'black')
add('sharp','already-sharp image',im)
im=Image.new('RGBA',(257*4,193*4),(255,0,255,0));d=ImageDraw.Draw(im);d.rounded_rectangle((120,100,900,650),80,fill=(50,160,215,255));d.ellipse((230,160,750,650),fill=(240,130,40,128));im=im.resize((257,193),Image.Resampling.LANCZOS);add('transparent','transparent asset',im)
# Exact pixel-budget boundary, crossing the stock 512px tile boundary horizontally.
im=Image.open(src/'object.png').resize((1024,512),Image.Resampling.LANCZOS);add('limit','near-limit / tiling',im,'object','expanded scene to exact 524288-source-pixel bound; performance fixture only')
manifest={'version':1,'notes':'Four inherited public/CC0 photographic sources; synthetic text/UI/line-art/illustration/alpha probes. Correlated derivatives, not a broad quality benchmark. No new third-party image downloads.','cases':cases}
for base in [raw,out]:(base/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
