import assert from 'node:assert/strict';
import { before,it } from 'node:test';
import { installBrowserGlobals } from '../../helpers/stub-browser-globals.js';
installBrowserGlobals();
let CanvasViewport,Rect,Point,promptPoint,beginPromptedGesture,movePromptedGesture,finishPromptedGesture;
before(async()=>{({CanvasViewport}=await import('../../../src/document/model/canvas-viewport.js'));({Rect}=await import('../../../src/core/math/rect.js'));({Point}=await import('../../../src/core/math/point.js'));({promptPoint,beginPromptedGesture,movePromptedGesture,finishPromptedGesture}=await import('../../../src/document/tools/prompted-selection-gesture.js'))});
function fixture(zoom=1,rotation=0,dpi=1){window.devicePixelRatio=dpi;const doc={width:513,height:317,toolOverlayState:{}},v=doc.pathViewport=new CanvasViewport(doc);v.zoomScale=zoom*dpi;v.rotationRadians=rotation;v.panOffset=new Point(23*dpi,-17*dpi);v.viewportRect=new Rect(0,0,901*dpi,713*dpi);return doc}
for(const dpi of [1,2,3])for(const zoom of [.25,1,2.75])for(const rotation of [0,Math.PI/7])it(`screen/document roundtrip at DPI ${dpi}, zoom ${zoom}, rotation ${rotation}`,()=>{const doc=fixture(zoom,rotation,dpi),screen=doc.pathViewport.docToScreenPoint(123.5,87.25),p=promptPoint(doc,screen);assert.ok(Math.abs(p.x-123.5)<1e-8);assert.ok(Math.abs(p.y-87.25)<1e-8);doc.pathViewport.viewportRect.width+=73;const next=doc.pathViewport.docToScreenPoint(123.5,87.25);assert.ok(Math.abs(promptPoint(doc,next).x-123.5)<1e-8)});
it('positive/Alt negative and box gestures use document coordinates, not screen scale',()=>{const doc=fixture(2,.2,2),tool={toolOptions:{}},calls=[],controller={openDocs:[doc],getSelectionJobs:()=>({submitPrompt:(d,p)=>calls.push([d,p])})};let pointer=doc.pathViewport.docToScreenPoint(30,40);beginPromptedGesture(tool,doc,{isPressed:()=>false},pointer);finishPromptedGesture(tool,doc,controller,pointer);assert.equal(calls[0][1].kind,'positive');assert.ok(Math.abs(calls[0][1].x-30)<1e-8);beginPromptedGesture(tool,doc,{isPressed:()=>true},pointer);finishPromptedGesture(tool,doc,controller,pointer);assert.equal(calls[1][1].kind,'negative');beginPromptedGesture(tool,doc,{isPressed:()=>false},pointer);pointer=doc.pathViewport.docToScreenPoint(100,120);movePromptedGesture(tool,doc,{...pointer,isDown:true});finishPromptedGesture(tool,doc,controller,pointer);const p=calls[2][1];assert.equal(p.kind,'box');assert.ok(Math.abs(p.width-70)<1e-8);assert.ok(Math.abs(p.height-80)<1e-8)});
it('tab switch or document close during gesture never redirects prompt',()=>{const doc=fixture(),other=fixture(),tool={toolOptions:{}},calls=[],controller={openDocs:[doc,other],getSelectionJobs:()=>({submitPrompt:()=>calls.push(1)})};const p={x:10,y:10};beginPromptedGesture(tool,doc,{isPressed:()=>false},p);finishPromptedGesture(tool,other,controller,p);assert.equal(calls.length,0);beginPromptedGesture(tool,doc,{isPressed:()=>false},p);controller.openDocs=[];finishPromptedGesture(tool,doc,controller,p);assert.equal(calls.length,0)});
