"""Bounded M4 acceptance corpus. Reuses reviewed M3 photos; synthetic labels are geometric, never inferred."""
from pathlib import Path
from PIL import Image, ImageDraw
import hashlib, json, sys
root=Path(__file__).resolve().parents[2]; src=root/'tests/fixtures/subject-corpus/v1'; out=root/'tests/fixtures/prompted-corpus/v1';out.mkdir(parents=True,exist_ok=True)
raw=Path(sys.argv[1]);raw.mkdir(parents=True,exist_ok=True)
parents={c['id']:c for c in json.loads((src/'manifest.json').read_text())['cases']};records=[]
def point(x,y,kind='positive'):return {'kind':kind,'x':x,'y':y}
def add(name,category,im,pos,neg,box,correction,source,label=None,derived=None):
 im=im.convert('RGBA');f=out/(name+'.png');im.save(f);w,h=im.size
 p=point(*pos);n=point(*neg,'negative');c=point(*correction)
 seq=[{'name':'point','points':[p],'box':None},{'name':'point-negative','points':[p,n],'box':None},{'name':'box','points':[],'box':box},{'name':'box-correction','points':[c],'box':box},{'name':'multiple-corrections','points':[p,n,c],'box':box}]
 rec={'id':name,'category':category,'file':f.name,'width':w,'height':h,'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'source':parents[source]['source'] if source in parents else source,'license':parents[source]['license'] if source in parents else 'CC0','derived':derived,'groundTruth':None,'sequences':seq}
 if label is not None:label.save(out/(name+'-label.png'));rec['groundTruth']=name+'-label.png'
 records.append(rec);(raw/(name+'.bin')).write_bytes(im.tobytes())
def box(x,y,w,h):return {'x':x,'y':y,'width':w,'height':h}
p=Image.open(src/'product.png');label=Image.open(src/'product-label.png')
add('isolated','single isolated object',p,(128,178),(30,150),box(78,36,102,245),(128,75),'product',label)
neighbor=Image.new('RGB',(513,321),(235,230,220));neighbor.paste(p,(0,0));neighbor.paste(p,(256,0));gt=Image.new('L',neighbor.size);gt.paste(label,(0,0))
add('neighbors','two similar neighboring products',neighbor,(128,178),(380,178),box(78,36,102,245),(128,75),'product',gt,'two copies of synthetic M3 product; target is left bottle')
people=Image.open(src/'people.png')
add('people','one of two people',people,(260,300),(370,290),box(205,130,135,300),(270,170),'people',derived='target is person on left')
# A deliberately constructed person/person occlusion stress case, not a natural independent photograph.
a=Image.open(src/'person.png').convert('RGB');occ=a.copy();foreground=a.crop((100,15,365,500)).resize((212,388));occ.paste(foreground,(270,124))
add('occluded-person','person partially behind another',occ,(190,300),(385,320),box(30,18,286,485),(204,96),'person',derived='manual rectangular portrait composite; target original left person; correlated stress case')
coffee=Image.open(src/'object.png');add('table','cup on cluttered table',coffee,(280,220),(430,300),box(155,35,265,285),(310,120),'object',derived='target cup, excluding saucer/spoon')
ring=Image.new('RGB',(321,257),(220,217,210));d=ImageDraw.Draw(ring);d.ellipse((68,32,253,222),fill=(180,70,28));d.ellipse((120,85,200,169),fill=(220,217,210));gt=Image.new('L',ring.size);d=ImageDraw.Draw(gt);d.ellipse((68,32,253,222),fill=255);d.ellipse((120,85,200,169),fill=0)
add('hole','object with interior negative space',ring,(87,124),(160,125),box(64,28,194,199),(227,125),'generated by scripts/m4/create-corpus.py',gt)
cat=Image.open(src/'fur.png');add('fur','pet/fur',cat,(220,150),(425,25),box(0,0,451,300),(350,195),'fur')
chair=Image.new('RGB',(321,321),(225,223,218));gt=Image.new('L',chair.size);d=ImageDraw.Draw(gt);d.rounded_rectangle((90,34,231,150),radius=8,fill=255);d.rectangle((83,148,239,171),fill=255);d.polygon([(90,169),(106,169),(94,295),(82,295)],fill=255);d.polygon([(216,169),(232,169),(243,295),(231,295)],fill=255);d.rectangle((104,196,229,204),fill=255);chair.paste(Image.new('RGB',chair.size,(36,100,132)),mask=gt)
add('thin','chair with thin legs/crossbar',chair,(160,100),(160,250),box(75,28,175,275),(90,266),'generated by scripts/m4/create-corpus.py',gt)
low=Image.open(src/'low-contrast.png');add('low-contrast','low contrast cup',low,(280,220),(430,300),box(155,35,265,285),(310,120),'low-contrast',derived=parents['low-contrast']['derived'])
boundary=cat.crop((65,30,400,285));add('boundary','object touching image boundary',boundary,(160,120),(320,10),box(0,0,335,255),(80,200),'fur',derived='tight cat crop touches all image boundaries')
occ=p.copy().convert('RGB');ImageDraw.Draw(occ).rectangle((135,140,238,290),fill=(135,145,115));gt=label.copy();ImageDraw.Draw(gt).rectangle((135,140,238,290),fill=0)
add('occluded-object','partially occluded product',occ,(118,178),(200,210),box(78,36,102,245),(128,75),'product',gt,'synthetic foreground block partially occludes bottle')
manifest={'version':1,'notes':'Four source photographs reused from reviewed M3 corpus; derived crops/contrast/composite stress cases and independent geometric synthetic labels. Eleven categories, five specified prompt sequences each. Not a broad or independent benchmark. Person occlusion is constructed, not a natural crowded photograph.','cases':records}
(out/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');(raw/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
