"""Create versioned M3 acceptance fixtures; photos and controlled synthetic stress cases.
Run with conversion-requirements.txt environment. No model output is a ground truth.
"""
from pathlib import Path
from urllib.request import urlopen, Request
from PIL import Image, ImageDraw, ImageEnhance
import hashlib, json, io
OUT=Path(__file__).resolve().parents[2]/'tests/fixtures/subject-corpus/v1'
OUT.mkdir(parents=True,exist_ok=True)
records=[]
def add(name,category,image,source,license,seed,label=None,derived=None):
    image=image.convert('RGBA'); path=OUT/(name+'.png'); image.save(path)
    rec={'id':name,'category':category,'file':path.name,'width':image.width,'height':image.height,'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'source':source,'license':license,'quickSelectSeed':seed,'derived':derived,'groundTruth':None}
    if label:
        label.save(OUT/(name+'-label.png'));rec['groundTruth']=name+'-label.png'
    records.append(rec)
def fetch(url):return Image.open(io.BytesIO(urlopen(Request(url,headers={'User-Agent':'PhotoSuite-M3-evaluation/1.0'})).read())).copy()
base='https://raw.githubusercontent.com/scikit-image/scikit-image/v0.24.0/skimage/data/'
a=fetch(base+'astronaut.png');c=fetch(base+'coffee.png');cat=fetch(base+'chelsea.png')
add('person','single person',a,base+'astronaut.png','Public domain NASA',[220,300])
url='https://upload.wikimedia.org/wikipedia/commons/6/66/Barack_Obama_and_Joe_Biden_running_in_the_Colonnade_of_the_White_House%2C_February_2014_%2813898117298%29.jpg'
m=fetch(url);m.thumbnail((768,768));add('people','multiple people',m,url,'Public domain US government; Pete Souza / White House. Evaluation only; no endorsement.',[250,300])
add('object','non-human object',c,base+'coffee.png','CC0; Rachel Michetti / scikit-image',[280,220])
add('fur','pet/fur',cat,base+'chelsea.png','CC0; Stefan van der Walt / scikit-image',[220,150])
add('hair','hair',a.crop((120,15,315,210)),base+'astronaut.png','Public domain NASA',[100,85],derived='crop of person; correlated stress case')
add('clutter','object on cluttered background',c.crop((0,0,590,395)),base+'coffee.png','CC0; Rachel Michetti / scikit-image',[280,220],derived='odd-dimension coffee crop; correlated stress case')
add('low-contrast','low contrast foreground',Image.blend(Image.new('RGB',c.size,(128,128,128)),c.convert('RGB'),.18),base+'coffee.png','CC0; Rachel Michetti / scikit-image',[280,220],derived='18 percent contrast against neutral gray')
add('dark','dark foreground/dark background',ImageEnhance.Brightness(cat).enhance(.22),base+'chelsea.png','CC0; Stefan van der Walt / scikit-image',[220,150],derived='22 percent brightness cat')
add('bright','bright foreground/bright background',Image.blend(Image.new('RGB',c.size,'white'),c.convert('RGB'),.18),base+'coffee.png','CC0; Rachel Michetti / scikit-image',[280,220],derived='18 percent image against white')
# Controlled product with an exact geometric label. Independent of model output.
label=Image.new('L',(257,321));d=ImageDraw.Draw(label);d.rounded_rectangle((82,100,174,275),radius=20,fill=255);d.rectangle((109,50,147,117),fill=255);d.rounded_rectangle((105,40,151,63),radius=5,fill=255)
product=Image.new('RGBA',label.size,(235,230,220,255));paint=Image.new('RGBA',label.size,(30,105,165,255));product.paste(paint,mask=label)
ImageDraw.Draw(product).rectangle((88,154,168,216),fill=(235,225,185,255))
add('product','product on plain background',product,'generated by create-corpus.py','CC0',[128,178],label=label)
# Alpha-bearing synthetic bottle; inference must not use transparent RGB garbage.
transparent=product.copy();alpha=label.point(lambda x: round(x*.55));transparent.putalpha(alpha)
add('transparent','partially transparent object',transparent,'generated by create-corpus.py','CC0',[128,178],label=alpha,derived='55 percent alpha bottle; tests source transparency, not optical glass matting')
(OUT/'manifest.json').write_text(json.dumps({'version':1,'notes':'Four independent photographs plus seven correlated crops/photometric or synthetic stress cases. No masks produced by inference are used as labels. Synthetic labels alone support quantitative scores. Real-photo quality requires visual review. Sources are resized only for the bounded evaluation.','cases':records},indent=2)+'\n')
