import assert from 'node:assert/strict';
import { it } from 'node:test';
import { createPromptedProvider } from '../../../src/features/modernization/prompted-provider.js';
function fixture(idle=10000){const workers=[];const provider=createPromptedProvider(()=>{const w={terminated:0,postMessage(m,t){this.message=m;this.transfers=t},terminate(){this.terminated++}};workers.push(w);return w},idle),completed=[],failed=[];const callbacks={complete:r=>completed.push(r),fail:e=>failed.push(e),progress:()=>{}};return{workers,provider,completed,failed,callbacks};}
const input=(sessionId='s')=>({rgba:new Uint8Array(4),sessionId});
const finish=(w,id='a',revision=1,sessionId='s')=>w.onmessage({data:{id,revision,result:{sessionId}}});
it('lazy worker, same-session warm reuse, transferred input, old identity rejection',()=>{const f=fixture();assert.equal(f.workers.length,0);const i=input();f.provider.start(i,f.callbacks,{id:'a',revision:1});const w=f.workers[0];assert.equal(w.transfers[0],i.rgba.buffer);finish(w,'old');assert.equal(f.completed.length,0);finish(w);f.provider.start(input(),f.callbacks,{id:'b',revision:2});assert.equal(f.workers.length,1);finish(w,'a',1);assert.equal(f.completed.length,1);finish(w,'b',2);assert.equal(f.completed.length,2);f.provider.dispose()});
it('Cancel during encode/decode retires realm and saved callback cannot display late output',()=>{const f=fixture();const stop=f.provider.start(input(),f.callbacks,{id:'a',revision:1}),w=f.workers[0],late=w.onmessage;assert.equal(stop(),true);assert.equal(w.terminated,1);late({data:{id:'a',revision:1,result:{sessionId:'s'}}});assert.equal(f.completed.length,0);f.provider.start(input(),f.callbacks,{id:'b',revision:2});assert.equal(f.workers.length,2);f.provider.dispose()});
it('wrong session completion fails closed; a new source retires previous worker',()=>{const f=fixture();f.provider.start(input(),f.callbacks,{id:'a',revision:1});finish(f.workers[0],'a',1,'wrong');assert.equal(f.failed.length,1);assert.equal(f.workers[0].terminated,1);f.provider.start(input(),f.callbacks,{id:'b',revision:2});finish(f.workers[1],'b',2);f.provider.start(input('new'),f.callbacks,{id:'c',revision:1});assert.equal(f.workers[1].terminated,1);f.provider.dispose()});
it('close/stale release only matching owner, idle releases automatically',async()=>{const f=fixture(5);f.provider.start(input(),f.callbacks,{id:'a',revision:1});finish(f.workers[0]);f.provider.releaseSession('different');assert.equal(f.workers[0].terminated,0);f.provider.releaseSession('s');assert.equal(f.workers[0].terminated,1);f.provider.start(input(),f.callbacks,{id:'b',revision:2});finish(f.workers[1],'b',2);await new Promise(r=>setTimeout(r,15));assert.equal(f.workers[1].terminated,1)});
for(const code of ['model-missing','model-corrupt','inference-failure'])it(code+' releases and recovers with fresh worker',()=>{const f=fixture();f.provider.start(input(),f.callbacks,{id:'a',revision:1});f.workers[0].onmessage({data:{id:'a',revision:1,error:{code}}});assert.equal(f.failed[0].code,code);assert.equal(f.workers[0].terminated,1);f.provider.start(input(),f.callbacks,{id:'b',revision:2});assert.equal(f.workers.length,2);f.provider.dispose()});
it('worker crash and startup error have useful failures',()=>{const f=fixture();f.provider.start(input(),f.callbacks,{id:'a',revision:1});f.workers[0].onerror({preventDefault(){}});assert.equal(f.failed[0].code,'worker-failure');createPromptedProvider(()=>{throw Error()}).start(input(),f.callbacks,{id:'b',revision:2});assert.equal(f.failed[1].code,'runtime-unavailable')});
