import assert from 'node:assert/strict';
import { before,it } from 'node:test';
import { installBrowserGlobals } from '../../helpers/stub-browser-globals.js';
import { fakeProvider,flushJobs } from './fake-provider.js';
import { validatePromptedInput,copyPromptedResult,reconstructPromptedMask } from '../../../src/features/modernization/prompted-workload.js';
installBrowserGlobals();
let Document,Rect,SelectionJobs,History;
before(async()=>{({Document}=await import('../../../src/document/model/document.js'));({Rect}=await import('../../../src/core/math/rect.js'));const {LayerSystem}=await import('../../../src/engine/layer-system.js');LayerSystem.webglEnabled=false;({SelectionJobs}=await import('../../../src/features/modernization/selection-jobs.js'));const {TrackerRegistry}=await import('../../../src/features/trackers/tracker-registry.js');History=TrackerRegistry.History;});
function fixture(){
 const doc=new Document('prompted.psd');doc.width=40;doc.height=30;doc.buffer=new Uint8Array(40*30*4);const layer=doc.newLayer();layer.rect=new Rect(3,4,5,3);layer.setName('Original');layer.buffer=new Uint8Array(60).fill(255);doc.setLayers([layer]);doc.selectedLayerIndices=[0];
 const controller={openDocs:[doc],getCurrentDoc:()=>doc,pointerState:{isDown:false}},fake=fakeProvider(),releases=[];Object.assign(fake.provider,{validateInput:validatePromptedInput,copyResult:copyPromptedResult,releaseSession:id=>releases.push(id)});
 const bridge=new SelectionJobs(controller,undefined,false,undefined,undefined,fake.provider);controller.getSelectionJobs=()=>bridge;
 const result=(call=fake.calls.at(-1),value=0)=>reconstructPromptedMask(call.input,new Float32Array(4*65536).fill(value),new Float32Array([0,1,0,0]));
 const prompt=(kind='positive',x=5,y=5)=>bridge.submitPrompt(doc,{kind,x,y});
 return {doc,layer,controller,bridge,history:new History(),result,prompt,releases,...fake};
}
it('accumulated positive, negative and box corrections are one transient session, Accept is exactly one M0 entry',async()=>{const f=fixture(),before=f.layer.buffer.slice();for(const p of [{kind:'positive',x:5,y:5},{kind:'positive',x:4,y:4},{kind:'negative',x:7,y:6},{kind:'box',x:3,y:4,width:5,height:3}]){const id=f.bridge.submitPrompt(f.doc,p);await flushJobs();f.calls.at(-1).complete(f.result());assert.equal(f.bridge.jobs.get(id).state,'preview');assert.equal(f.doc.history.length,1)}assert.equal(f.calls[3].input.points.length,3);assert.ok(f.calls[3].input.box);assert.equal(f.calls[3].revision,4);const id=f.calls[3].id;assert.equal(f.bridge.jobs.accept(id),true);assert.equal(f.doc.history.length,2);const accepted=f.doc.selectionMask.channel.slice();assert.deepEqual(f.layer.buffer,before);assert.equal(f.doc.toolOverlayState.objectSelectionPrompts,null);f.history.stepHistoryBackward(f.doc);assert.equal(f.doc.selectionMask,null);f.history.stepHistoryForward(f.doc);assert.deepEqual(f.doc.selectionMask.channel,accepted);assert.equal(f.calls.length,4);assert.equal(f.releases.length,1)});
for(const action of ['discard','cancel'])it(action+' preserves existing selection/history and releases embedding ownership',async()=>{const f=fixture();f.doc.selectionMask={rect:new Rect(1,1,2,2),channel:new Uint8Array([255,0,128,255])};const prior=f.doc.selectionMask,id=f.prompt();await flushJobs();f.calls[0].complete(f.result());f.bridge.jobs[action](id);assert.equal(f.doc.selectionMask,prior);assert.equal(f.doc.history.length,1);assert.equal(f.doc.toolOverlayState.jobSelectionPreview,null);assert.equal(f.bridge.sessions.size,0);assert.equal(f.releases.length,1)});
it('B then A then duplicate B completion keeps B preview and no history',async()=>{const f=fixture(),a=f.prompt();await flushJobs();const ra=f.result();const b=f.prompt('negative',7,6);await flushJobs();const rb=f.result(f.calls[1],3);f.calls[1].complete(rb);const selected=f.doc.toolOverlayState.jobSelectionPreview;f.calls[0].complete(ra);f.calls[1].complete(f.result(f.calls[1],-3));assert.equal(f.doc.toolOverlayState.jobSelectionPreview,selected);assert.equal(selected.jobId,b);assert.equal(f.bridge.jobs.get(a).state,'cancelled');assert.equal(f.calls[1].revision,2);assert.equal(f.doc.history.length,1)});
it('cancel running request revokes acceptance and ignores late completion',async()=>{const f=fixture(),id=f.prompt();await flushJobs();const r=f.result();f.bridge.jobs.cancel(id);f.calls[0].complete(r);assert.equal(f.bridge.jobs.get(id).state,'cancelled');assert.throws(()=>f.bridge.jobs.accept(id));assert.equal(f.doc.toolOverlayState.jobSelectionPreview,undefined);assert.equal(f.doc.history.length,1)});
const mutations={pixels:f=>f.layer.buffer[51]--,origin:f=>f.layer.rect.x++,channels:f=>f.doc.activeChannels=[0],replacement:f=>f.doc.layers=[f.doc.newLayer()],target:f=>f.doc.selectedLayerIndices=[],history:f=>f.doc.history[0]={},geometry:f=>f.doc.width++,maskHistory:f=>f.doc.history.push({})};
for(const [name,mutate] of Object.entries(mutations))it('stale '+name+' blocks result and drops session/cache',async()=>{const f=fixture(),id=f.prompt();await flushJobs();const r=f.result();mutate(f);f.calls[0].complete(r);assert.equal(f.bridge.jobs.get(id).state,'stale');assert.equal(f.bridge.sessions.size,0);assert.equal(f.releases.length,1);assert.equal(f.doc.selectionMask,null)});
it('stale source at Accept is rechecked without waiting for periodic tick',async()=>{const f=fixture(),id=f.prompt();await flushJobs();f.calls[0].complete(f.result());f.layer.buffer[51]--;assert.equal(f.bridge.jobs.accept(id),false);assert.equal(f.releases.length,1);assert.equal(f.doc.history.length,1)});
it('switch tabs preserves source ownership; starting another document retires prior session',async()=>{const f=fixture(),g=fixture();f.controller.openDocs.push(g.doc);f.prompt();await flushJobs();f.controller.getCurrentDoc=()=>g.doc;f.calls[0].complete(f.result());assert.ok(f.doc.toolOverlayState.jobSelectionPreview);assert.equal(g.doc.toolOverlayState.jobSelectionPreview,undefined);const next=f.bridge.submitPrompt(g.doc,{kind:'positive',x:5,y:5});assert.equal(f.doc.toolOverlayState.jobSelectionPreview,null);assert.equal(f.releases.length,1);await flushJobs();f.calls[1].complete(f.result());assert.equal(g.doc.toolOverlayState.jobSelectionPreview.jobId,next)});
it('close document cancels late mutation and drops retained resources',async()=>{const f=fixture(),id=f.prompt();await flushJobs();const r=f.result();f.bridge.close(f.doc);f.controller.openDocs=[];f.calls[0].complete(r);assert.equal(f.bridge.jobs.get(id).state,'cancelled');assert.equal(f.doc.history.length,1);assert.equal(f.bridge.sessions.size,0);assert.ok(f.releases.length)});
it('new object clears prompts without history and wrong session output is rejected',async()=>{const f=fixture();f.prompt();await flushJobs();f.calls[0].complete(f.result());f.bridge.resetPrompted(f.doc);const b=f.prompt();await flushJobs();assert.equal(f.calls[1].input.points.length,1);const r=f.result();r.sessionId='wrong';f.calls[1].complete(r);assert.equal(f.bridge.jobs.get(b).state,'failed');assert.equal(f.doc.history.length,1)});
it('accepted prompted selection works with manual Remove Background and PSD exact mask roundtrip',async()=>{const {removeBackgroundFromSelection}=await import('../../../src/features/trackers/exact-result-tracker.js');const {PSDParser}=await import('../../../src/document/formats/psd/psd-parser.js');const {RenderBuffer}=await import('../../../src/core/render-buffer.js');const {TrackerRegistry}=await import('../../../src/features/trackers/tracker-registry.js');const {registerTrackers}=await import('../../../src/features/trackers/register-trackers.js');registerTrackers(TrackerRegistry);const f=fixture(),id=f.prompt(),before=f.layer.buffer.slice();await flushJobs();f.calls[0].complete(f.result());f.bridge.jobs.accept(id);removeBackgroundFromSelection(f.controller);assert.equal(f.doc.history.length,3);const mask=f.layer.getMask().clone();assert.deepEqual(f.layer.buffer,before);f.history.stepHistoryBackward(f.doc);assert.equal(f.layer.getMask(),null);f.history.stepHistoryForward(f.doc);assert.deepEqual(f.layer.getMask().channel,mask.channel);const b=new RenderBuffer(),n=PSDParser.serialize(f.doc,b,[false,false,false,false]),reopened=new Document('reopened.psd');PSDParser.parse(b.data.slice(0,n).buffer,reopened);assert.deepEqual(reopened.layers[0].buffer,before);assert.deepEqual(reopened.layers[0].getMask().channel,mask.channel)});
it('M3 and M4 retain separate providers, identities and session ownership',async()=>{const f=fixture(),subject=fakeProvider(),prompted=fakeProvider(),released=[];Object.assign(prompted.provider,{validateInput:validatePromptedInput,copyResult:copyPromptedResult,releaseSession:id=>released.push(id)});subject.provider.validateInput=(await import('../../../src/features/modernization/subject-workload.js')).validateSubjectInput;const bridge=new SelectionJobs(f.controller,undefined,false,undefined,subject.provider,prompted.provider);const p=bridge.submitPrompt(f.doc,{kind:'positive',x:5,y:5});await flushJobs();const s=bridge.submitSubject(f.doc);await flushJobs();assert.equal(bridge.jobs.get(p).state,'cancelled');assert.equal(bridge.jobs.get(s).operation,'segment.subject');assert.equal(subject.calls.length,1);assert.equal(prompted.calls.length,1);assert.equal(released.length,1);assert.equal(f.doc.toolOverlayState.objectSelectionPrompts,null);bridge.jobs.cancel(s);const next=bridge.submitPrompt(f.doc,{kind:'positive',x:5,y:5});await flushJobs();assert.equal(prompted.calls.length,2);assert.equal(subject.calls.length,1);assert.equal(bridge.jobs.get(next).operation,'segment.prompted')});
